# Project Information
site_name: The Self-Taught Dev
site_author: Tim MacKay
site_description: Studying computer science and sharing the journey
site_url: https://theselftaughtdev.io

# Copyright
copyright: Copyright &copy; 2024 Tim MacKay

# Custom CSS
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

# Custom JS
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# Additional dirs to auto-load changes
watch:
  - includes

# Configuration
theme:
  name: material
  language: en
  favicon: assets/favicon.png
  logo: assets/brandmark_white.svg
  font:
    text: Poppins
    code: Roboto Mono
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: light mode
        icon: material/lightbulb
      primary: custom
      accent: custom
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        name: dark mode
        icon: material/lightbulb-outline
      primary: custom
      accent: custom
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.indexes
    # enable XHR loading
    - navigation.instant
    - navigation.instant.progress
    # add button to jump to top of page
    - navigation.top
    # update URL with anchors as user scrolls
    - navigation.tracking
    # scroll the sidebar table of contents as the user scrolls
    - toc.follow
    # enhance search
    - search.suggest
    - search.highlight

# Additional Configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theselftaughtdev42
      name: Tim's Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/theselftaughtdev/
      name: Tim's LinkedIn
    - icon: fontawesome/brands/medium
      link: https://medium.com/@theselftaughtdev
      name: Tim's Medium Page
    - icon: simple/devdotto
      link: https://dev.to/theselftaughtdev
      name: Tim's Dev.to Page
    - icon: simple/dailydotdev
      link: https://app.daily.dev/theselftaughtdev
      name: Tim's Daily.dev
  
  analytics:
    provider: google
    property: fake-token

# Extensions
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
      title: On this page
  - footnotes
  # enable assorted functionality
  - attr_list
  - md_in_html
  # enable inline icons an emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # enable call-outs
  - admonition
  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.tasklist:
      custom_checkbox: true
  # enable abbreviations in a glossary
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/gen/abbreviations.md

# Plugins
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#FF7F29" 
        color: "#F4F4F4"
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - glightbox
  - blog:
      blog_toc: true
      post_excerpt: required
      post_url_date_format: yyyy
      categories_allowed:
        - TODO
        - Contemplations
        - Learning
        - Computer Science Fundamentals
      # don't show the draft posts when building the site for prod
      # this is the default but I'm being explicit in case it changes in the future
      draft: false

hooks:
  - hooks/socialmedia.py

# Site Navigation
nav:
  - Home: index.md
  - Self-Taught Pathway: pathway.md
  - Blog:
    - blog/index.md
  - about.md
not_in_nav: |
  health-check.html